; This file was auto-generated by drush make
core = 7.x

api = 2
projects[] = "drupal"

projects[esdportal_str][type] = "module"
projects[esdportal_str][subdir] = "features"
projects[esdportal_str][download][type] = "git"
projects[esdportal_str][download][url] = "https://github.com/bnchdrff/esdportal_str.git"
projects[esdportal_str][download][branch] = "7.x-1.x"

projects[esdportal_migrate][type] = "module"
projects[esdportal_migrate][subdir] = "custom"
projects[esdportal_migrate][download][type] = "git"
projects[esdportal_migrate][download][url] = "https://github.com/bnchdrff/esdportal_migrate.git"
projects[esdportal_migrate][download][branch] = "7.x-1.x"

projects[acl][subdir] = "contrib"
projects[acl][version] = "1.0"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.3"

projects[captcha][subdir] = "contrib"
projects[captcha][version] = "1.0-beta2"

projects[node_clone][subdir] = "contrib"
projects[node_clone][version] = "1.0-rc1"

projects[content_access][subdir] = "contrib"
projects[content_access][version] = "1.2-beta2"

projects[date][subdir] = "contrib"
projects[date][version] = "2.6"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.1"

projects[extlink][subdir] = "contrib"
projects[extlink][version] = "1.12"

projects[features][subdir] = "contrib"
projects[features][version] = "2.0-rc1"

projects[feeds][subdir] = "contrib"
projects[feeds][version] = "2.0-alpha8"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "1.3"

projects[hidden_captcha][subdir] = "contrib"
projects[hidden_captcha][version] = "1.0"

projects[imce][subdir] = "contrib"
projects[imce][version] = "1.7"

projects[imce_wysiwyg][subdir] = "contrib"
projects[imce_wysiwyg][version] = "1.0"

projects[job_scheduler][subdir] = "contrib"
projects[job_scheduler][version] = "2.0-alpha3"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "1.0"

projects[link][subdir] = "contrib"
projects[link][version] = "1.1"

projects[location][subdir] = "contrib"
projects[location][version] = "3.0-rc1"

projects[location_feeds][subdir] = "contrib"
projects[location_feeds][version] = "1.6"

projects[logintoboggan][subdir] = "contrib"
projects[logintoboggan][version] = "1.3"

projects[mailsystem][subdir] = "contrib"
projects[mailsystem][version] = "2.34"

projects[mimemail][subdir] = "contrib"
projects[mimemail][version] = "1.0-alpha2"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[redirect][subdir] = "contrib"
projects[redirect][version] = "1.0-rc1"

projects[services][subdir] = "contrib"
projects[services][version] = "3.4"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[taxonomy_revision][subdir] = "contrib"
projects[taxonomy_revision][version] = "1.0"

projects[video_embed_field][subdir] = "contrib"
projects[video_embed_field][version] = "2.0-beta5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.7"

projects[webform][subdir] = "contrib"
projects[webform][version] = "4.0-alpha6"

projects[workspace][subdir] = "contrib"
projects[workspace][version] = "1.x-dev"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"



; Modules
projects[devel][type] = "module"
projects[devel][subdir] = "contrib"
projects[devel][download][type] = "git"
projects[devel][download][url] = "git://git.drupal.org/project/devel.git"
projects[devel][download][branch] = "7.x-1.x"

projects[location][type] = "module"
projects[location][subdir] = "contrib"
projects[location][download][type] = "git"
projects[location][download][url] = "git://git.drupal.org/project/location.git"
projects[location][download][branch] = "7.x-3.x"

projects[migrate][type] = "module"
projects[migrate][subdir] = "contrib"
projects[migrate][download][type] = "git"
projects[migrate][download][url] = "git://git.drupal.org/project/migrate.git"
;projects[migrate][download][branch] = "7.x-2.x"
projects[migrate][download][revision] = "aab31f3af8c44b37b5355bfba4732eb87b414269"

projects[migrate_d2d][type] = "module"
projects[migrate_d2d][subdir] = "contrib"
projects[migrate_d2d][download][type] = "git"
projects[migrate_d2d][download][url] = "git://git.drupal.org/project/migrate_d2d.git"
;projects[migrate_d2d][download][branch] = "7.x-2.x"
projects[migrate_d2d][download][revision] = "494211f6d4ffb492c828c3b19ed7f57b30d8bf0c"

projects[uuid][type] = "module"
projects[uuid][subdir] = "contrib"
projects[uuid][download][type] = "git"
projects[uuid][download][url] = "git://git.drupal.org/project/uuid.git"
projects[uuid][download][revision] = "4bbf92d8c07485492c0f1065cb3647db492e1029"

projects[uuid_features][type] = "module"
projects[uuid_features][subdir] = "contrib"
projects[uuid_features][download][type] = "git"
projects[uuid_features][download][url] = "git://git.drupal.org/project/uuid_features.git"
projects[uuid_features][download][revision] = "f88f1035b28c1d7e4acdfb87b563b943c0c3d911"

; Themes
projects[esd][type] = "theme"
projects[esd][download][type] = "git"
projects[esd][download][url] = "chili@pm.theworkdept.com:excellent-schools-detroit.git"
projects[esd][download][branch] = "portal"

projects[omega][type] = "theme"
projects[omega][download][type] = "git"
projects[omega][download][url] = "git://git.drupal.org/project/omega.git"
;projects[omega][download][branch] = "7.x-4.x"
projects[omega][download][revision] = "71d02c9f0d0fd0a251f648ffbb29b23bee1967ce"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.easing][download][type] = ""
libraries[jquery.easing][download][url] = ""
libraries[jquery.easing][directory_name] = "jquery.easing"
libraries[jquery.easing][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.domwindow][download][type] = ""
libraries[jquery.domwindow][download][url] = ""
libraries[jquery.domwindow][directory_name] = "jquery.domwindow"
libraries[jquery.domwindow][type] = "library"

